[package]
name = "yaca-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
portable-pty = { version = "0.9.0", features = ["serde_support"] }
rig = { version = "0.42.0", features = ["rmcp"] }
schemars = "1.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smol_str = { version = "0.3.6", features = ["serde"] }
sysinfo = "0.39.6"
wezterm-term = { git = "https://github.com/yaca-developers/wezterm.git", rev = "d9c5846a" }
termwiz = { git = "https://github.com/yaca-developers/wezterm.git", rev = "d9c5846a" }
thiserror = "2.0.19"
tokio = { version = "1.53", features = ["fs", "macros", "rt-multi-thread"] }
tracing = { version = "0.1", optional = true }
unicode-normalization = "0.1.25"
url = "2.5.8"
finl_unicode = "1.4.0"
num-traits = "0.2.19"
ordered-float = "5.3.0"
trait-variant = "0.1.3"
uuid = "1.24.0"
futures = "0.3.34"
rmcp = { version = "2", features = ["client"] }
derive_builder = "0.20.2"

[dev-dependencies]
test-log = { version = "0.2.21", default-features = false, features = [
	"trace",
] }

[features]
default = ["tracing"]
tracing = ["dep:tracing"]
