[package]
name = "yaca-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53", features = ["fs", "rt-multi-thread"] }
tracing = { version = "0.1", optional = true }

[dev-dependencies]
test-log = { version = "0.2.21", default-features = false, features = [
	"trace",
] }

[features]
default = ["tracing"]
tracing = ["dep:tracing"]
